[tool.poetry]
name = "noxylwebsite"
version = "0.1.0"
description = ""
authors = ["levwilliamsmm <levwilliamsmm@mindsmechanical.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.124.0"
uvicorn = {extras = ["standard"], version = "^0.38.0"}
jinja2 = "^3.1.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
